name: mynewsapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_route: ^5.0.4
 
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1

dev_dependencies:
  auto_route_generator: ^5.0.4
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
